//
//  DeveloperSettingsView.swift
//  OpenIntelligence
//
//  Simplified, native Settings-style layout (Form + Sections)
//

import SwiftUI

struct DeveloperSettingsView: View {
    @AppStorage("loggingLevel") private var loggingLevelRaw: Int = LoggingConfiguration.Level.info.rawValue
    @AppStorage("enablePipelineLogs") private var enablePipelineLogs: Bool = true
    @AppStorage("enablePerformanceLogs") private var enablePerformanceLogs: Bool = true
    @AppStorage("enableLLMLogs") private var enableLLMLogs: Bool = true
    @AppStorage("enableStreamingLogs") private var enableStreamingLogs: Bool = false
    @AppStorage("enableVectorDBLogs") private var enableVectorDBLogs: Bool = true
    @AppStorage("enableTelemetryLogs") private var enableTelemetryLogs: Bool = true

    private var loggingLevel: LoggingConfiguration.Level {
        get { LoggingConfiguration.Level(rawValue: loggingLevelRaw) ?? .info }
        set {
            loggingLevelRaw = newValue.rawValue
            applyLoggingSettings()
        }
    }

    var body: some View {
        Form {
            // Logging Level (compact, native controls)
            Section("Console Logging Level") {
                Picker("Logging Level", selection: $loggingLevelRaw) {
                    Text("Silent (Production)").tag(LoggingConfiguration.Level.silent.rawValue)
                    Text("Error Only").tag(LoggingConfiguration.Level.error.rawValue)
                    Text("Warning").tag(LoggingConfiguration.Level.warning.rawValue)
                    Text("Info (Default)").tag(LoggingConfiguration.Level.info.rawValue)
                    Text("Debug (Verbose)").tag(LoggingConfiguration.Level.debug.rawValue)
                    Text("Verbose (Maximum)").tag(LoggingConfiguration.Level.verbose.rawValue)
                }
                .onChange(of: loggingLevelRaw) { _, _ in applyLoggingSettings() }

                currentLevelInfo
                    .listRowInsets(EdgeInsets(top: 6, leading: 0, bottom: 6, trailing: 0))

                Text("Controls overall verbosity of console output. Set to “Silent” for production to minimize log spam.")
                    .font(.footnote)
                    .foregroundColor(.secondary)
            }

            // Category toggles
            Section("Logging Categories") {
                Toggle("RAG Pipeline", isOn: $enablePipelineLogs)
                    .onChange(of: enablePipelineLogs) { _, _ in applyLoggingSettings() }
                Toggle("Performance Metrics", isOn: $enablePerformanceLogs)
                    .onChange(of: enablePerformanceLogs) { _, _ in applyLoggingSettings() }
                Toggle("LLM Generation", isOn: $enableLLMLogs)
                    .onChange(of: enableLLMLogs) { _, _ in applyLoggingSettings() }
                Toggle("Token Streaming", isOn: $enableStreamingLogs)
                    .onChange(of: enableStreamingLogs) { _, _ in applyLoggingSettings() }
                Toggle("Vector Database", isOn: $enableVectorDBLogs)
                    .onChange(of: enableVectorDBLogs) { _, _ in applyLoggingSettings() }
                Toggle("Telemetry Events", isOn: $enableTelemetryLogs)
                    .onChange(of: enableTelemetryLogs) { _, _ in applyLoggingSettings() }

                Text("Tip: Disabling “Token Streaming” significantly reduces console spam during generation.")
                    .font(.footnote)
                    .foregroundColor(.secondary)
            }

            // Presets
            Section("Presets") {
                HStack {
                    Button("Production") { applyProductionPreset() }
                        .buttonStyle(.bordered)
                    Button("Development") { applyDevelopmentPreset() }
                        .buttonStyle(.bordered)
                    Button("Debug") { applyDebugPreset() }
                        .buttonStyle(.bordered)
                }
                .font(.callout)
                Text("Quick presets for common scenarios. Production: minimal logs. Development: balanced. Debug: maximum detail.")
                    .font(.footnote)
                    .foregroundColor(.secondary)
            }

            // System Logs note
            Section("System Logs") {
                Toggle("Suppress iOS Warnings", isOn: .constant(false))
                    .disabled(true)
                Text("System warnings (NSMapGet, UIKeyboard, Metal HUD, etc.) are generated by iOS frameworks and cannot be suppressed in app code. Use Xcode’s console filters.")
                    .font(.footnote)
                    .foregroundColor(.secondary)
            }

            // Current config summary
            Section("Current Configuration") {
                LabeledContent("Active Level", value: loggingLevel.description)
                LabeledContent("Categories Enabled", value: "\(enabledCategoriesCount)")
                HStack {
                    Text("Estimated Log Volume")
                    Spacer()
                    Text(estimatedLogVolume)
                        .foregroundColor(logVolumeColor)
                }
            }
        }
        .navigationTitle("Developer Settings")
        #if os(iOS)
        .navigationBarTitleDisplayMode(.inline)
        #endif
        .onAppear { applyLoggingSettings() }
    }

    // MARK: - Computed UI

    @ViewBuilder
    private var currentLevelInfo: some View {
        switch loggingLevel {
        case .silent:
            InfoBox(icon: "moon.zzz.fill", text: "All console output disabled (production mode)", color: .gray)
        case .error:
            InfoBox(icon: "xmark.circle.fill", text: "Only critical errors will be logged", color: .red)
        case .warning:
            InfoBox(icon: "exclamationmark.triangle.fill", text: "Errors and warnings will be logged", color: .orange)
        case .info:
            InfoBox(icon: "info.circle.fill", text: "Errors, warnings, and key operations (recommended)", color: .blue)
        case .debug:
            InfoBox(icon: "ant.circle.fill", text: "Verbose logging for development and debugging", color: .purple)
        case .verbose:
            InfoBox(icon: "text.bubble.fill", text: "Maximum verbosity - all logs including streaming", color: .green)
        }
    }

    private var enabledCategoriesCount: Int {
        var count = 0
        if enablePipelineLogs { count += 1 }
        if enablePerformanceLogs { count += 1 }
        if enableLLMLogs { count += 1 }
        if enableStreamingLogs { count += 1 }
        if enableVectorDBLogs { count += 1 }
        if enableTelemetryLogs { count += 1 }
        return count
    }

    private var estimatedLogVolume: String {
        if loggingLevel == .silent { return "None" }
        if loggingLevel == .error { return "Very Low" }

        let categoryMultiplier = Double(enabledCategoriesCount) / 6.0

        switch loggingLevel {
        case .warning:
            return categoryMultiplier > 0.5 ? "Low–Medium" : "Low"
        case .info:
            return categoryMultiplier > 0.7 ? "Medium" : "Medium–Low"
        case .debug:
            return enableStreamingLogs ? "Very High" : "High"
        case .verbose:
            return "Extreme"
        default:
            return "Unknown"
        }
    }

    private var logVolumeColor: Color {
        switch estimatedLogVolume {
        case "None", "Very Low", "Low": return .green
        case "Low–Medium", "Medium–Low", "Medium": return .blue
        case "High": return .orange
        case "Very High", "Extreme": return .red
        default: return .gray
        }
    }

    // MARK: - Actions

    private func applyLoggingSettings() {
        // Update global logging configuration
        LoggingConfiguration.currentLevel = loggingLevel

        // Update enabled categories
        var categories: Set<LoggingConfiguration.Category> = []
        if enablePipelineLogs { categories.insert(.pipeline) }
        if enablePerformanceLogs { categories.insert(.performance) }
        if enableLLMLogs { categories.insert(.llm) }
        if enableStreamingLogs { categories.insert(.streaming) }
        if enableVectorDBLogs { categories.insert(.vectorDB) }
        if enableTelemetryLogs { categories.insert(.telemetry) }

        LoggingConfiguration.enabledCategories = categories

        print("✅ [Developer Settings] Logging configuration updated")
        print("   Level: \(loggingLevel)")
        print("   Categories: \(categories.map { "\($0)" }.joined(separator: ", "))")
    }

    private func applyProductionPreset() {
        loggingLevelRaw = LoggingConfiguration.Level.error.rawValue
        enablePipelineLogs = false
        enablePerformanceLogs = false
        enableLLMLogs = false
        enableStreamingLogs = false
        enableVectorDBLogs = false
        enableTelemetryLogs = false
        applyLoggingSettings()
    }

    private func applyDevelopmentPreset() {
        loggingLevelRaw = LoggingConfiguration.Level.info.rawValue
        enablePipelineLogs = true
        enablePerformanceLogs = true
        enableLLMLogs = true
        enableStreamingLogs = false  // Keep disabled to reduce spam
        enableVectorDBLogs = true
        enableTelemetryLogs = false
        applyLoggingSettings()
    }

    private func applyDebugPreset() {
        loggingLevelRaw = LoggingConfiguration.Level.verbose.rawValue
        enablePipelineLogs = true
        enablePerformanceLogs = true
        enableLLMLogs = true
        enableStreamingLogs = true
        enableVectorDBLogs = true
        enableTelemetryLogs = true
        applyLoggingSettings()
    }
}

// MARK: - Supporting Views

struct InfoBox: View {
    let icon: String
    let text: String
    let color: Color

    var body: some View {
        HStack(spacing: 12) {
            Image(systemName: icon)
                .foregroundColor(color)
                .font(.title3)

            Text(text)
                .font(.caption)
                .foregroundColor(.secondary)

            Spacer()
        }
        .padding(10)
        .background(color.opacity(0.08))
        .clipShape(RoundedRectangle(cornerRadius: 8, style: .continuous))
    }
}

// MARK: - Extensions

extension LoggingConfiguration.Level: CustomStringConvertible {
    var description: String {
        switch self {
        case .silent: return "Silent"
        case .error: return "Error"
        case .warning: return "Warning"
        case .info: return "Info"
        case .debug: return "Debug"
        case .verbose: return "Verbose"
        }
    }
}

#Preview {
    NavigationView {
        DeveloperSettingsView()
    }
}
